### ISSUE TITLE
Wire split by line

### ISSUE THREAD

**Issue by GabrielJMS** [Dessia-tech/volmdlr#1030]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
The method split_by_line of WireMixin returns wires with None as primitives.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

from dessia_common.core import DessiaObject

contour = DessiaObject.load_from_file("contour_split_by_line_contour.json")
line = DessiaObject.load_from_file("contour_split_by_line_line.json")

split  = contour.split_by_line(line)

[contour_split_by_line.zip](https://github.com/Dessia-tech/volmdlr/files/12464518/contour_split_by_line.zip)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by WirajanDASILVA** [comment]
it seems like it's ok now 
<img width="628" alt="image" src="https://github.com/Dessia-tech/volmdlr/assets/77811165/7808915b-8276-4e1b-9037-f52f1bc82480">
