### ISSUE TITLE
Bug : VolumeModel and BoundingBox

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/volmdlr#1109]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Taking this BoundingBox, converting it to a VolumeModel containing a Block using Block.from_bounding_box, and taking the BoundingBox of this VolumeModel result in two different BoundingBox.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
```
import volmdlr.core
import volmdlr.primitives3d
bbox1 = volmdlr.core.BoundingBox(-0.0271021, 1.0271020999999998, -0.4024024, 0.8024024000000001, -0.0261011, 0.5261011000000001)
block = volmdlr.primitives3d.Block.from_bounding_box(bbox1)
volmol = volmdlr.core.VolumeModel([block])
bbox2 = volmol.bounding_box
print(bbox1 == bbox2)
```
Even using BoundingBox.is_close implemented in [fix_bbox_equality](https://github.com/Dessia-tech/volmdlr/tree/fix_bbox_equality) don't return True in this case.

* **What is the expected behavior?**
I expect this code to print True. At least using the `is_close` method.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  564e71bb9fba4cab5c2d04c7594e3dd805ab65df or 5d23f6a56a241904df58aa3a9f8ce3e11daea44b
  - python version: 3.8

**Comment by pgibertini** [comment]
This is due to an offset added in the `BoundingBox.from_bounding_box` method:


```python
class BoundingBox(dc.DessiaObject):
    # ...
    @classmethod
    def from_bounding_boxes(cls, bounding_boxes: List["BoundingBox"], name: str = '') -> "BoundingBox":
        """
        Creates a bounding box that contains multiple bounding boxes.

        :param bounding_boxes: A list of bounding boxes that need to be contained.
        :type bounding_boxes: list of BoundingBox
        :return: A new bounding box that contains all the input bounding boxes.
        :rtype: BoundingBox
        """
        xmin = min(bb.xmin for bb in bounding_boxes)
        xmax = max(bb.xmax for bb in bounding_boxes)
        x_length = xmax - xmin
        xmin -= x_length * 0.001
        xmax += x_length * 0.001

        ymin = min(bb.ymin for bb in bounding_boxes)
        ymax = max(bb.ymax for bb in bounding_boxes)
        y_length = ymax - ymin
        ymin -= y_length * 0.001
        ymax += y_length * 0.001

        zmin = min(bb.zmin for bb in bounding_boxes)
        zmax = max(bb.zmax for bb in bounding_boxes)
        z_length = zmax - zmin
        zmin -= z_length * 0.001
        zmax += z_length * 0.001
        return cls(xmin, xmax, ymin, ymax, zmin, zmax, name=name)
```

@WirajanDASILVA what is the motivation of doing that ?

**Comment by pgibertini** [comment]
Maybe the default comportment can be let without the `* 0.001` and a parameter can control this offset ?
Or we can create a method `scale` to the `BoundingBox` object that can perform this scaling operation when needed ?

**Comment by WirajanDASILVA** [comment]
sometimes, bboxes for faces (created using from_bounding_boxes) can be a little bit smaller than the actual face, what can lead to errors when verifying if a point belongs to the that face, for example. That was the main reason the box was made slightly bigger in this method.

**Comment by WirajanDASILVA** [comment]
@pgibertini

**Comment by pgibertini** [comment]
Can you identify for which faces it is doing this ?
I think the good solution is to increase the size only in specific cases

**Comment by WirajanDASILVA** [comment]
[test_planeface_point_belongs.json](https://github.com/Dessia-tech/volmdlr/files/13297532/test_planeface_point_belongs.json)

**Comment by pgibertini** [comment]
I will modify the `BoundingBox.from_bounding_boxes` method to solve this issue, and create a specific method to add an offset to the bounding box when needed : for `PlaneFace3D.point_belongs` and `BSpineFace3D.bouding_box`
