### ISSUE TITLE
Shell Unittest

### ISSUE THREAD

**Issue by GabrielJMS** [Dessia-tech/volmdlr#1120]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
tests/shells/test_closedshell3d.py

The shell used in this test seems inconsistent.
![image](https://github.com/Dessia-tech/volmdlr/assets/89979482/104b2d8c-10d4-461b-8d28-2ac933daf36b)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by WirajanDASILVA** [comment]
issue has been fixed

![Image](https://github.com/Dessia-tech/volmdlr/assets/77811165/c9dfbe52-ba39-470a-a436-d83f4610d4bf)



![Image](https://github.com/Dessia-tech/volmdlr/assets/77811165/bef90c39-f835-4801-9e17-485f5c57a999)
