### ISSUE TITLE
Mesh3D: fusion of multiple Mesh3D into one

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#1328]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the expected behavior?**
Possibility to add a Mesh3D into an other one, without necesseraly checking if triangles are in double.

* **What is the motivation / use case for changing the behavior?**
From stl file we can load one Mesh3D per Stl but in project we fusion those stl files (thanks to OpenTriangleShell3D by doing a sum of faces)

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  latest
  - python version: 3.9.13

**Comment by pgibertini** [comment]
Already available as `Mesh3D.from_meshes`

**Comment by MackJoly** [comment]
Thanks for the quick answer !
