### ISSUE TITLE
Reading stl print -> optional

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#1349]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
Imposed print when reading stl file thanks to Stl.from_binary_stream

* **What is the expected behavior?**
Have the choice to print or not the message "reading stl ..."

* **What is the motivation / use case for changing the behavior?**
Not user friendly in platform

* **Possible fixes**
add a parameter in the function: verbose: Bool = False (or True)

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  latest
  - python version: 3.9.13

**Comment by pgibertini** [comment]
Hello Mack

If you use the Mesh3D to read STL there is no print and it will be much faster

**Comment by MackJoly** [comment]
Hello Pierre,
I am trying the Mesh3D method but I need to be sure that the behavior is similar in order to not break my algorithm

**Comment by pgibertini** [comment]
It should be. 

Mesh3D should has method to convert to OpenTriangleShell3D / ClosedTriangleShell3D and so you can compare the result.

**Comment by MackJoly** [comment]
The behavior is the same. Do you know if it is possible to have a function to clean flat triangles (triangles that are read but in fact they have 2 points in common or points are very close, cf Stl.clean_flat_triangles() ) in Mesh3D ?

**Comment by MackJoly** [comment]
I see that there is the method Mesh3D.remove_degenerate_triangles, thank for the support !
