### ISSUE TITLE
BSpline3D extrusion

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#157]
* **I'm submitting a ...**
  - [X] feature request

From a BSpline, having the possibility to extrude a circle as Sweep do but with BSpline3D.

**Comment by MackJoly** [comment]
In another way, i would like to have the product of two BSpline3D : here a circle and a way that is a BSpline3D.
To do that, perhaps the better way is to use a BSplineFace3D with u a circle and v the BSpline3D.

**Comment by MackJoly** [comment]
First improvement available in sweepspline branch

**Comment by MackJoly** [comment]
![image](https://user-images.githubusercontent.com/61141035/141177808-8d244c77-b7eb-455a-ac4d-5b9d1c5332c9.png)
![image](https://user-images.githubusercontent.com/61141035/141177858-0d0cf31f-3299-45af-bbb3-813d46e76264.png)

**Comment by WirajanDASILVA** [comment]
@MackJoly, is this still in progress? can I add it to the ROADMAP.md file?

**Comment by MackJoly** [comment]
Yes you can add it to the roadmap, i have to spend a few time on it to be sure that it is okay
