### ISSUE TITLE
Generate babylonjs without opening the file in a browser

### ISSUE THREAD

**Issue by DumouchelP** [Dessia-tech/volmdlr#182]
* **I'm submitting a ...**
  - [ ] bug report
  - [x ] feature request

* **What is the current behavior?**
When you generate a babylonjs the browser open the html file

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
An option to be able to generate the file while not opening it with a browser

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
Better: A separate method to save as the babylon html with a specified filepath
the babylonjs method use this method to save to a tmpfile
