### ISSUE TITLE
Edge width too big when rendering far from the origin

### ISSUE THREAD

**Issue by pgibertini** [Dessia-tech/volmdlr#195]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

When I render with babylonjs a RevolvedProfile far from the origin of the landmark, the edge width is too big which is not aesthetic. I can manually redefine the edge width but when I move the object, it changes automatically to a too high value.

![image](https://user-images.githubusercontent.com/56967597/135835503-dfa6e7c7-3984-49bb-bd61-74b9404f6863.png)

When I render with babylonjs a RevolvedProfile on (0,0,0), there is no problem and the edge width seems to be fix with a value of 0.02.

Also, the edge seems to not be represented when I change its color.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Render a RevolvedProfile far from the origin (for example in (1,1,1)).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
Is this fix?
