### ISSUE TITLE
cloud2d.to_polygon remove points

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#213]
cloud2d.to_polygon remove points 
This is a strange behavior. 
list of points is transmitted in to_polygon?

Script for reproduction: scripts/cloud/cloud2d_concav.py
https://drone-opensource.dessia.tech/Dessia-tech/volmdlr/1568/1/2

**Comment by MackJoly** [comment]
The aim of cloud2d.to_polygon is to return a simplify polygon
If the list of points have less than 2 points or if the area is zero, the return is None because there are checks in other function that interpretes them well
