### ISSUE TITLE
Grid of point class

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#218]
Grid of points if used for bspline but not theorized with a class
- list of points
- number u & number v

**Comment by WirajanDASILVA** [comment]
@masfaraud, @sbendjebla Has this issue been solved? Or should I add it to our roadmap?

**Comment by sbendjebla** [comment]
@WirajanDASILVA Actually, I created the object Grid2D with PR #334 
I'm now updating the code (especially in faces.py) with this new object in this PR #362

**Comment by sbendjebla** [comment]
I'll close the issue when the PR is merged !

**Comment by WirajanDASILVA** [comment]
alright. I'll then add it. Thanks @sbendjebla for the rapid response.

**Comment by WirajanDASILVA** [comment]
will it be available already for the next release, you think? @sbendjebla

**Comment by sbendjebla** [comment]
It has been resolved in #362 (**merged**)
