### ISSUE TITLE
vm.Vector3D.remove_duplicate not working well ?

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#228]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
The method delete points even if they are one iteration

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
import volmdlr as vm
points = [vm.O3D, vm.X3D, vm.Z3D, vm.Y3D, vm.X3D + vm.Y3D, vm.X3D + vm.Z3D*2, vm.Z3D*2 + vm.Y3D*5 + vm.X3D]
new_points = vm.Vector3D.remove_duplicate(points)
![image](https://user-images.githubusercontent.com/61141035/142214417-04d9cccd-2333-4043-9aba-65606d5d7ea3.png)

* **What is the expected behavior?**
Keeping points that are not in double

* **What is the motivation / use case for changing the behavior?**
Cleaning PointCloud3D efficiently.

* **Possible fixes**
I checked the method : 
    @classmethod
    def remove_duplicate(cls, points):
        dict_ = {p.approx_hash() : p for p in points}
        return list(dict_.values())

and 
![image](https://user-images.githubusercontent.com/61141035/142216143-523e787a-2571-4860-9da1-56d43c061bae.png)

* **Please tell us about your environment:**
  
  - branch: sweespline
  - commit:  merge fromd ev
  - python version: 3.8.8

**Comment by AxelRinghausen** [comment]
Solved on branch _remove_duplicates_.
