### ISSUE TITLE
Import STEP File: Face3D with inner contours

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/volmdlr#267]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**

The **Inner contours** of **Face3D**, imported form a STEP file **_are not considered_**

Here are examples > [Face3D.zip](https://github.com/Dessia-tech/volmdlr/files/7807425/Face3D.zip)
-PlaneFace3D
-BSplineFace3D

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by AxelRinghausen** [comment]
PlaneFace3D
![image](https://user-images.githubusercontent.com/50665039/150172311-d55dadbc-1b8f-470b-892e-ba4f32a802bc.png)

**Comment by sbendjebla** [comment]
You can merge your branch with this branch `scripts_inner_contours`, to get the scripts for testing before PR

**Comment by sbendjebla** [comment]
Importing STEP File with inner contours is **good** ! 
![image](https://user-images.githubusercontent.com/68638483/167610686-7ff1b242-7166-4a3b-a28a-5ee754990a6e.png)

But, neither **cut_by_line**, nor **babylonjs** work correctly 
![image](https://user-images.githubusercontent.com/68638483/167610626-3cd96688-f8cd-4b81-910d-d5871a853ae7.png)
![image](https://user-images.githubusercontent.com/68638483/167610758-1b6780e5-fc91-44cb-9871-b1d7dfc2106d.png)

**Comment by sbendjebla** [comment]
Fixed with #284
