### ISSUE TITLE
Simplify/ refactor code

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#269]
Error of quality code:
Following functions are still too complex:

```
volmdlr/step.py
    M 343:4 Step.instanciate - F
    M 504:4 Step.to_volume_model - E
volmdlr/faces.py
    M 5914:4 ClosedShell3D.new_valid_faces - F
    M 2054:4 BSplineSurface3D.bsplinecurve3d_to_2d - E

```

**Comment by sbendjebla** [comment]
What do these Letters & Numbers (_**in bold**_) mean ??

volmdlr/primitives.py
    M 42:4 RoundedLineSegments._primitives - **F (41)**
volmdlr/step.py
    M 343:4 Step.instanciate - **F (46)**
    M 504:4 Step.to_volume_model - **E (31)**

**Comment by masfaraud** [comment]
It's the Cyclomatic complexity score and it is translated in a mark, https://radon.readthedocs.io/en/latest/commandline.html#the-cc-command

**Comment by masfaraud** [comment]
It pass drone now, thx
