### ISSUE TITLE
Scary code in Surface3Dcontour3d_to_2d

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#292]
Code is scary:
 - undefined variables
- unused variables

![image](https://user-images.githubusercontent.com/14061753/150772489-372ab05e-9e52-438c-a275-958080c6a4a8.png)
![image](https://user-images.githubusercontent.com/14061753/150772577-d547918f-873f-4f94-be50-80385e19ec8a.png)

**Comment by WirajanDASILVA** [comment]
@AxelRinghausen, I see a PR has been merged on the issue. Has it been totally solved, or should I add it to our ROADMAP?

**Comment by sbendjebla** [comment]
@masfaraud to be closed ?
