### ISSUE TITLE
Empty method

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#293]
Code of method is commented
Either delete (comment) method def or put some content

https://github.com/Dessia-tech/volmdlr/blob/aea7ac38373ee2c4b22d20179d5f8187eabfa50d/volmdlr/faces.py#L2290

**Comment by sbendjebla** [comment]
I've deleted it in this [PR](https://github.com/Dessia-tech/volmdlr/pull/259) because a new one had been developed.
