### ISSUE TITLE
Extrusion problem in babylonjs display

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#3]
Script  [extrusion 3](https://github.com/Dessia-tech/volmdlr/blob/7b406ae2f6f79c3862447f3d842a1a29f558218f/scripts/extrusion3.py) documents this issue:

The contours to be extruded are weel defined in YZ plane and extruded towards X. The Freecad export works, babylonjs fails

![image](https://user-images.githubusercontent.com/14061753/71740040-6636f200-2e5b-11ea-8ecc-7ef8b4231c27.png)
![image](https://user-images.githubusercontent.com/14061753/71740072-85358400-2e5b-11ea-932d-6cc8f9bd658f.png)

**Comment by AxelRinghausen** [comment]
Fixed in #10
