### ISSUE TITLE
Circle discretization too low

### ISSUE THREAD

**Issue by pgibertini** [Dessia-tech/volmdlr#302]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

working good on commit: Merge branch 'dev' into stream_ci

* **What is the current behavior?**

![image](https://user-images.githubusercontent.com/56967597/151335689-83131e50-4d0d-4d73-be1e-9f597626648f.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Render a face from a circle coutour
circle = vm.wires.Circle3D(frame_1, r1)
face = vm.faces.Plane3D(frame_1).face_from_contours3d([circle])

* **What is the expected behavior?**

![image](https://user-images.githubusercontent.com/56967597/151336378-ba38de94-ccb1-40a5-9fa9-bb6d4949b69a.png)

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  Merge pull request #291 from Dessia-tech/pylint
  - python version: 3.9

**Comment by masfaraud** [comment]
should be fix by #344
