### ISSUE TITLE
Bug: Surface2D.cut_by_line with inner contours

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/volmdlr#307]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Surface2D.cut_by_line don't cut properly

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

[surface2d.json.tar.gz](https://github.com/Dessia-tech/volmdlr/files/7977468/surface2d.json.tar.gz)
```
from volmdlr import Point2D
from volmdlr.edges import Line2D
from dessia_common import DessiaObject


surface2d = DessiaObject.load_from_file('/home/axel/Bureau/surface2d.json')
line1 = Line2D(Point2D(0.40, 0), Point2D(0.40, 1))
line2 = Line2D(Point2D(0.41, 0), Point2D(0.41, 1))

ax = surface2d.plot()
line1.plot(ax=ax)

ax = surface2d.plot()
line2.plot(ax=ax)

surfaces = surface2d.cut_by_line(line1)
surfaces[0].plot()
surfaces[1].plot()

surfaces = surface2d.cut_by_line(line2)
surfaces[0].plot()
surfaces[1].plot()
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: holes
  - commit: bb7ab27aa9f29e9272fd0fb52f0a2b237d2dc111
  - python version: 3.8

![image](https://user-images.githubusercontent.com/50665039/151947195-5ba85cca-b884-4cbb-9317-33b84cadbdac.png)
![image](https://user-images.githubusercontent.com/50665039/151947378-e0d2d83e-dc5f-44dc-80a3-4a1c2c368e83.png)

**Comment by sbendjebla** [comment]
In BSplineCurve2D.line_crossings, use:
