### ISSUE TITLE
to_stl empty with more than 2 faces

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#337]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
Stl file saved empty

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

import volmdlr.faces as vmf
tri1, tri2 = vmf.Triangle3D(vm.O3D, vm.X3D, vm.Y3D), vmf.Triangle3D(vm.Z3D, vm.X3D, vm.Y3D)
shell_tri = vmf.ClosedShell3D([tri1, tri2])
#shell_tri.babylonjs()
shell_tri.to_stl('test1')

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
should be fixed in https://github.com/Dessia-tech/volmdlr/commit/8cc910244789ab3171a9e057b4b44689aa2965d6
