### ISSUE TITLE
faces.PlaneFace3D.face_intersections() does not consider holes

### ISSUE THREAD

**Issue by WirajanDASILVA** [Dessia-tech/volmdlr#376]
* **I'm submitting a ...**
  - [X] bug report
  - [X] feature request

* **What is the current behavior?**
when cutting a ClosedShell3D like the following with a plane, the cut is not well done.
![image](https://user-images.githubusercontent.com/77811165/166232245-3249003a-e524-4db0-a291-c93255a845f9.png)
![image](https://user-images.githubusercontent.com/77811165/166232279-ac8537d2-8bd5-4fe4-be7e-400d5d3a2894.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
We should have a face corresponding to the full intersection between the closedshell3d and the plane

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**
I believe face_intersections already finds all intersections. but it does not return all of them for certain reasons. Maybe go from there

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by sbendjebla** [comment]
@WirajanDASILVA It should be closed ?
