### ISSUE TITLE
Import STEP: Primitives not following each other

### ISSUE THREAD

**Issue by BayssetGuillaume** [Dessia-tech/volmdlr#438]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
The method to_volume_model() applied to a step file give the following error : 'Primitives not following each other in contour'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  
  - python version:

**Comment by WirajanDASILVA** [comment]
Do you have the steps to reproduce the problem? If I am not mistaking, it is an error raised when trying to order primitives of a contour...
