### ISSUE TITLE
Read_Step error -> ValueError: list.remove(x): x not in list l.593

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#441]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

```
File "c:\users\mack\documents\git\volmdlr\volmdlr\step.py", line 593, in to_volume_model
    [shell_nodes.remove(node) for node in not_shell_nodes]
  File "c:\users\mack\documents\git\volmdlr\volmdlr\step.py", line 593, in <listcomp>
    [shell_nodes.remove(node) for node in not_shell_nodes]
ValueError: list.remove(x): x not in list
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Check the same linked in volmdlr channel on Slack, step files are present there

* **What is the motivation / use case for changing the behavior?**

Customer need

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  228e0e5d274549baab9b9dca5fd9a37dc568b16c
  - python version:

**Comment by sbendjebla** [comment]
@MackJoly to be closed ?

**Comment by MackJoly** [comment]
Yup, I didn't have the problem anymore
