### ISSUE TITLE
Footprint of one closed shell on another closed shell

### ISSUE THREAD

**Issue by BayssetGuillaume** [Dessia-tech/volmdlr#447]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**
Returns if exists (at least 2 coincident faces between the 2 closed shells) the closed shell 1 with the footprint of the closed shell 2.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
There is a method to compute the intersection wires. It is used for boolean operations
