### ISSUE TITLE
primitive3d.ClosedRoundedLineSegment3D.__init__ feels odd

### ISSUE THREAD

**Issue by AxelRinghausen** [Dessia-tech/volmdlr#450]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
```
File "/home/axel/Documents/git/volmdlr/volmdlr/primitives3d.py", line 145, in __init__
    volmdlr.primitives.RoundedLineSegments.__init__(
TypeError: __init__() got multiple values for argument 'closed'
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: master
  - commit: 60ca0db58511fc937ef18352261c8f955e4a7c41
  - python version: 3.8.10

**Comment by WirajanDASILVA** [comment]
hello, @AxelRinghausen ? Do you have the means to reproduce de error?
