### ISSUE TITLE
contour2D.translate_inplace bug

### ISSUE THREAD

**Issue by ziedsallem** [Dessia-tech/volmdlr#464]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
the translation_inplace of a contour2D which contains an arc just translates the segments but the arc which remains has its place

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
import volmdlr as vm
import volmdlr.edges as vmedges
import volmdlr.wires as vmwires

rls = volmdlr.primitives2d.OpenedRoundedLineSegments2D([vm.Point2D(0,2), vm.Point2D(1,1), vm.Point2D(2,1), vm.Point2D(3,2)],
                                                                                                 {})
arc = vmedges.Arc2D(vm.Point2D(0,2), vm.Point2D(2,3), vm.Point2D(3,2))
contour2d = vmwires.Contour2D(rls.primitives + [arc])
contour2d.translation_inplace(vm.Point2D(0, 2))
contour2d.plot()

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: volmdlr/em_mesh
  - commit:  
  - python version: 3.8

**Comment by WirajanDASILVA** [comment]
fixed in PR #470 
![image](https://user-images.githubusercontent.com/77811165/193410408-2042cca9-ec0a-4f8c-8a00-4dc2d9d6173e.png)
