### ISSUE TITLE
Create a class for bounding rectangle

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#467]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
bounding rectangle gives xmin, xmax, ymin, ymax
There is no method to know if a point is inside the bounding rectangle

* **What is the motivation / use case for changing the behavior?**
Having an object like for bounding box will allow to attach methods

**Comment by WirajanDASILVA** [comment]
This would also be implemented in core.py?

**Comment by masfaraud** [comment]
Next to BoundingBox class maybe?

**Comment by sbendjebla** [comment]
https://github.com/Dessia-tech/volmdlr/pull/480 is merged to dev !
@masfaraud  can we close this issue ?

**Comment by sbendjebla** [comment]
@masfaraud, @GabrielJMS to be closed ?

**Comment by sbendjebla** [comment]
Since https://github.com/Dessia-tech/volmdlr/pull/480 is merged to dev, can you please check and close the issue if the bug is fixed ?
