### ISSUE TITLE
Add to the FreeCAD Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [Dessia-tech/volmdlr#514]
* **I'm submitting a ...**
  - [x] feature request

* **What is the motivation / use case for changing the behavior?**
	* Streamlining installation of 3rd party dependencies 
	* Exposure of the addon to the FreeCAD community at large

### Prerequisites
- [ ] A `package.xml` file is necessary https://wiki.freecadweb.org/Package_Metadata
- [ ] 3rd party dependencies need to be reviewed to see how they can be installed

The FreeCAD Addon Manager has its own repository at https://github.com/FreeCAD/FreeCAD-addons/

**Comment by luzpaz** [comment]
Looks like 3rd party deps are listed in `setup.py`  
https://github.com/Dessia-tech/volmdlr/blob/master/setup.py#L118-L131

**Comment by luzpaz** [comment]
any interest in this?

**Comment by WirajanDASILVA** [comment]
Hello @luzpaz, could you explain a little bit more what you need?

**Comment by luzpaz** [comment]
@WirajanDASILVA all is explained in https://wiki.freecad.org/Package_Metadata

**Comment by luzpaz** [comment]
![Screenshot_20230307_084132](https://user-images.githubusercontent.com/4140247/223439685-451e869a-249e-4ef0-89a2-daaa3964a41d.png)

Note: LICENSE file is GPL3
