### ISSUE TITLE
Complex CAO automatic simplification 

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#527]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
Possibility to have a wrapping version a complex CAO
Limitations : 
- If the CAO has holes, they are not taken into account
- Triangles number related to slice number
- gap between wrapping's slice that creates not smooth surfaces
PS : Do not take into account holes, the result is from a boolean
![image](https://user-images.githubusercontent.com/61141035/200957228-20048bde-2011-4439-b69c-096856f40d10.png)
![image](https://user-images.githubusercontent.com/61141035/200957352-277f36c1-2d34-4849-be6a-4446500fd590.png)

* **What is the expected behavior?**

To debate !

What are the needs ?

- Approximate a complex CAO in order to operate on it (piping around with distance check, boolean operations, point belongs)
- Attenuate the size by simplifying it (easier insertion in platform, quicker display loading)
- No need to have a mm precision, big picture is easier to develop bot and propose concept
- No space lost : take into account holes in simplify CAO
- Simplification must have the lower triangles/faces/surfaces -> using only cubic volum ? No curve to lower the number

**Comment by masfaraud** [comment]
What are the assumptions?
* type of faces?  only Triangles? PlaneFaces? Whatever

Some usecase and expected behavior definition are needed

**Comment by pgibertini** [comment]
@MackJoly does the new features in the cad_simplification module respond to the use case ?
you can see example usage in [this script directory ](https://github.com/Dessia-tech/volmdlr/tree/testing/scripts/cad_simplification)

**Comment by MackJoly** [comment]
@pgibertini I will check it !

**Comment by MackJoly** [comment]
I tried it and I have the same error as described in the following issue: https://github.com/Dessia-tech/volmdlr/issues/1251

**Comment by MackJoly** [comment]
Hi @pgibertini ! I tried the TripleExtrusionSimplify and it doesn't answer to my need. The simplification is too simple and not near the original CAD
Is it possible to have parameters to select how many slice we want in each direction ? As it is done in volmdlr.cloud.PointCloud3D.to_shell ?

**Comment by pgibertini** [comment]
Hi @MackJoly 

I recommend you to use AlphaWrapSimplify, as it will more fit your needs. It is parametrable such as described in the image below. 

It is available on testing and will be released in 0.16.0. 

![IMG_1420](https://github.com/Dessia-tech/volmdlr/assets/56967597/78f2ed32-becb-48fd-96ab-6e21871537cd)

**Comment by MackJoly** [comment]
AlphaWrapSimplify answer well my needs indeed !

**Comment by MackJoly** [comment]
OK for me, I close the ticket, everything on master 0.16.0
