### ISSUE TITLE
Fix: PlaneFace3D.line_intersections

### ISSUE THREAD

**Issue by WirajanDASILVA** [Dessia-tech/volmdlr#531]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
When a Line3D intersects face in the face's border, intersection is not considered. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
`
import volmdlr as vm
import volmdlr.primitives3d as primitives3d

bx2 = primitives3d.Block(
    vm.Frame3D(vm.Point3D(0, 0, 0), vm.Vector3D(0.1, 0, 0), vm.Vector3D(0, 0.1, 0), vm.Vector3D(0, 0, 0.1)),
    color=(0.1, 0.1, 0.1), alpha=0.6)
bx2=bx2.frame_mapping(vm.Frame3D(vm.Point3D(-0.06, -0.06, -0.06), vm.X3D, vm.Y3D, vm.Z3D), 'old')
closed_shell = vm.faces.ClosedShell3D(bx2.primitives)
closed_shell.alpha = 0.2

line3d = vm.edges.LineSegment3D(vm.Point3D(-0.11, -0.11, -0.06), vm.Point3D(-0.01499999999999999, -0.0049999999999999906, 0.14500000000000002))

vol = vm.core.VolumeModel([closed_shell, vm.wires.Wire3D([line3d])])
vol.babylonjs()

intersections = []
for face in closed_shell.primitives:
    line = line3d.to_line()
    pts_inter = face.line_intersections(line)
    if pts_inter:
        intersections.extend(pts_inter)
ax = closed_shell.plot()
for p in intersections:
    p.plot(ax, 'r')
print('number intersection {}'.format(len(intersections)))
`

* **What is the expected behavior?**
For the use case, three intersections were expected, but only one found.

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by sbendjebla** [comment]
@WirajanDASILVA to be closed ?
