### ISSUE TITLE
Create a straight_line_area method for ArcEllipse2D

### ISSUE THREAD

**Issue by GabrielJMS** [Dessia-tech/volmdlr#533]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
The method isn't implemented for ArcEllipse2D

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version: 3.10

**Comment by WirajanDASILVA** [comment]
already solved here https://github.com/Dessia-tech/volmdlr/blob/2c631acdac78ed2dacb4422902de18085d77c586/volmdlr/edges.py#L3366
