### ISSUE TITLE
Import STEP File: RationalBSplineSurface

### ISSUE THREAD

**Issue by sbendjebla** [Dessia-tech/volmdlr#549]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
![STEP_AA-T_1](https://user-images.githubusercontent.com/68638483/203361890-3149be01-cb45-44c7-8c33-088f07340ba3.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by WirajanDASILVA** [comment]
@sbendjebla It seems there is something related to that  in dev. could test it out, please?

**Comment by sbendjebla** [comment]
It seems that the step files are correctly read, but there is a problem with model.plot(), like this:
![image](https://user-images.githubusercontent.com/68638483/212297706-ea7e5a46-0a00-49c9-bd53-9004b4fda427.png)
![image](https://user-images.githubusercontent.com/68638483/212297764-73701682-b73d-45eb-9967-d517ad9f5c26.png)

**Comment by GabrielJMS** [comment]
Thank you very much for those precisions @sbendjebla . I'm submitting a pull request to fix this issue.
![image](https://user-images.githubusercontent.com/89979482/213672359-7e644c4d-6106-4b2a-86db-cd254bbe83e2.png)
![image](https://user-images.githubusercontent.com/89979482/213677681-0aa10037-b644-4b18-b999-76ad522cc335.png)
![image](https://user-images.githubusercontent.com/89979482/213677837-1ee10312-0ef7-4e1e-86ee-e22efb45a02e.png)
![image](https://user-images.githubusercontent.com/89979482/213678138-07fdf10a-62fa-47ca-8d3e-959b166771b5.png)
![image](https://user-images.githubusercontent.com/89979482/213678219-091c75a1-72a6-4121-a6de-d90638ab6809.png)

**Comment by sbendjebla** [comment]
Thanks. It works !
