### ISSUE TITLE
Missing some faces after substract boolean  operations on a bounding box

### ISSUE THREAD

**Issue by BayssetGuillaume** [Dessia-tech/volmdlr#553]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
It' missing some faces on a closed shell returns after successive substract boolean operations.
In the enclosed zip file there are 2 volume models containing closed shells for testing the bug.
The code for testing:

compo_primitives_for_assembly = DessiaObject.load_from_file("sensors.json")
cube = DessiaObject.load_from_file("cube.json")
cube = cube.primitives[0]

for primitive in compo_primitives_for_assembly.primitives:
    cube = cube.subtract_to_closed_shell(primitive)[0]
cube.color = (1, 0.1, 0.1)
cube.alpha = 0.6
cube.name = "BSI"

[volume_models.zip](https://github.com/Dessia-tech/volmdlr/files/10102814/volume_models.zip)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: sed_project_faces
  - commit:  
  - python version:

**Comment by sbendjebla** [comment]
@BayssetGuillaume 
Since #556 is merged to dev, can you please check and close the issue if the bug is fixed ?
