### ISSUE TITLE
copy method for Cylinder

### ISSUE THREAD

**Issue by DumouchelP** [Dessia-tech/volmdlr#61]
* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
develop a copy method for Cylinder maybie this kind of method ?
def copy(self):
     return Cylinder(self.position.copy(), self.axis.copy(), self.radius, self.length, self.color, self.alpha, self.name)

And bug in RevoluteProfile with
x = axis.deterministic_unit_normal_vector()

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
should be done
