### ISSUE TITLE
Bug intersection Line3D

### ISSUE THREAD

**Issue by DumouchelP** [Dessia-tech/volmdlr#64]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Bug in intersection return None with the following script

p1, p2, p3, p4 = vm.Point3D([-0.086, 0.11399999999999999, 0.21]),vm.Point3D([-0.086, 0.114, 0.17]), vm.Point3D([-0.086, -0.126, 0.2042857142857143]), vm.Point3D([-0.086, 0.124, 0.2042857142857143])
l1=vm.Line3D(p1,p2)
l2=vm.Line3D(p3,p4)
l1.Intersection(l2)

with the following image :
![image](https://user-images.githubusercontent.com/26141839/81873306-c2cdba80-957b-11ea-8be0-94e355187feb.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
Is this corrected?
