### ISSUE TITLE
BSplinecurve3D - point at abscissa different of curvature function

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#729]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
I have a BezierCurve3D and I wanted to evaluate the curvature at the middle. I evaluated the middle point from middle_point and the curvature function, points are different

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Here is what I did : 

single_wire = BezierCurve3D #available in zip folder

point_mid = single_wire.path.middle_point()
curv_mid, pt = single_wire.path.curvature(0.5, point_in_curve = True)

ax = single_wire.path.plot()
point_mid.plot(ax=ax,color='r')
pt.plot(ax=ax,color='m')
![image](https://user-images.githubusercontent.com/61141035/225355723-9845d02f-a73b-4530-b276-b102e1d93461.png)

* **What is the expected behavior?**
same point

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  0.8.1.dev821+g022f6bb1
  - python version: 3.9.13
[single_wire.zip](https://github.com/Dessia-tech/volmdlr/files/10981551/single_wire.zip)

**Comment by WirajanDASILVA** [comment]
it seems it has been already fixed. 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/77811165/231269045-188fbffb-6865-427d-9a83-6f59eef922ce.png">
