### ISSUE TITLE
Check if revolve profile works well

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/volmdlr#836]
* **I'm submitting a ...**
  - [x] potential bug report
  - [ ] feature request

* **What is the current behavior?**

Revolving a rectangle to create a cylinder may fail with radius = 0.01

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**
Creates a unit test to check if revolve profile works in this simple case

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by WirajanDASILVA** [comment]
I have added a raise ValueError to avoid the error caused when The normal vector of the Revolution's contour frame is parallel to the axis of revolution.
