### ISSUE TITLE
Sweep with non smooth path

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/volmdlr#939]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
When I try to sweep a circular contour with a non smooth path, an error occured

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

You can use the OpenRoundedLineSegments3D and the Contour2D in the following.zip file
Then you can apply: sweep = Sweep(section, path)
sweep.babylonjs()
[sweep.zip](https://github.com/Dessia-tech/volmdlr/files/11982819/sweep.zip)

* **What is the expected behavior?**
Only cylinders, no tores, it is not a problem if there are empty zone because of no tores

* **What is the motivation / use case for changing the behavior?**
Update Dessia's package

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: dev
  - commit:  latest
  - python version: 3.9.13

**Comment by masfaraud** [comment]
What is the log?
