### ISSUE TITLE
Bug on frame_mapping for block

### ISSUE THREAD

**Issue by DumouchelP** [Dessia-tech/volmdlr#99]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
bug with frame_mapping with copy=False impact shell_intersection
see branch dev_bug with the script script/distance/shell_intersection.py

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by masfaraud** [comment]
fix in b2407fdcbdd5b250293fa7d83f0be30da1e1ad2b: sheel_intersection script assert pass
